include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Code Style & Consistency
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    always_use_package_imports: true
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    sort_constructors_first: true
    use_decorated_box: true

    # Best Practices & Optimization
    avoid_redundant_argument_values: true
    avoid_slow_async_io: true
    avoid_void_async: true
    unnecessary_await_in_return: true
    unawaited_futures: true
    unnecessary_lambdas: true
    avoid_catches_without_on_clauses: true
    avoid_dynamic_calls: true
    avoid_empty_else: true
    avoid_function_literals_in_foreach_calls: true
    avoid_relative_lib_imports: true
    avoid_types_as_parameter_names: true
    unnecessary_this: true
    void_checks: true
    avoid_print: false
